services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - redis

#Add an api service to the compose.yaml file with the image build from the rust project in the api folder
  api:
    build: ./api
    restart: always
    ports:
      - '8000:8000'
    networks:
      - db
      - redis

networks:
  db:
  redis:

