services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - redis

networks:
  db:
  redis:

